image: gradle:8.1.1-jdk17-alpine

variables:
  GOOGLE_CLI_URL: https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew
  - apk update && apk add protoc

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - develop
    - main
  script:
    - ./gradlew shadowJar

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  only:
    - main
  script:
    - wget -O gcloud-sdk.tar.gz $GOOGLE_CLI_URL
    - tar -xzf gcloud-sdk.tar.gz
    - ./google-cloud-sdk/install.sh
    - export PATH=$PATH:$PWD/google-cloud-sdk/bin
    - gcloud components install app-engine-java
    - gcloud config set project $GOOGLE_PROJECT_ID
    - echo $GOOGLE_SERVICE_ACCOUNT > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - ./gradlew appengineDeploy

after_script:
  - rm -rf gcloud-sdk.tar.gz google-cloud-sdk gcloud-service-key.json