image: gradle:8.1.1-jdk17-alpine

variables:
  GOOGLE_CLI_URL: https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
  GRPC_JAVA_PROTOC_GEN_URL: https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.57.2/protoc-gen-grpc-java-1.57.2-linux-x86_64.exe

before_script:
  - export PATH="/usr/local/bin:$PATH"
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew
  - apk update && apk add protoc
  - cd /usr/local/bin
  - wget $GRPC_JAVA_PROTOC_GEN_URL -O protoc-gen-grpc-java.exe
  - chmod +x protoc-gen-grpc-java.exe

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - develop
    - main
  script:
    - ./gradlew shadowJar

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  only:
    - main
  script:
    - wget -O gcloud-sdk.tar.gz $GOOGLE_CLI_URL
    - tar -xzf gcloud-sdk.tar.gz
    - ./google-cloud-sdk/install.sh
    - export PATH=$PATH:$PWD/google-cloud-sdk/bin
    - gcloud components install app-engine-java
    - gcloud config set project $GOOGLE_PROJECT_ID
    - echo $GOOGLE_SERVICE_ACCOUNT > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - ./gradlew appengineDeploy

after_script:
  - rm -rf gcloud-sdk.tar.gz google-cloud-sdk gcloud-service-key.json